# Generated by Django 3.2.3 on 2021-05-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='high_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='high_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
