# Generated by Django 3.2.3 on 2021-05-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210519_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='high_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='high_bid',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
    ]
