# Generated by Django 3.2.3 on 2021-05-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210520_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='high_bid',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
