# Generated by Django 3.2.3 on 2021-05-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210521_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_watchlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_items', to='auctions.watchlist'),
        ),
    ]
