# Generated by Django 3.2.3 on 2021-05-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user_watchlist',
        ),
    ]
