# Generated by Django 3.2.3 on 2021-05-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_watchlist_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.watchlist'),
        ),
    ]
