# Generated by Django 3.2.3 on 2021-05-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210522_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.Listing'),
        ),
    ]
