# Generated by Django 3.2.3 on 2021-05-26 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
