# Generated by Django 3.2.3 on 2021-05-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20210526_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_bid',
        ),
    ]
