# Generated by Django 3.2.3 on 2021-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20210529_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
